FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Github_test

This is a change; just entered to see how it shows up in GitHub.

Here is another addition. This should show up in the add_lorem_ipsum branch

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque in dui ante. Nullam egestas est sed ex ornare faucibus. Praesent in odio eu nunc viverra ultrices. Sed sollicitudin neque diam, eget eleifend lacus ullamcorper a. Aliquam blandit egestas risus vitae dignissim. Donec convallis eu magna ac malesuada. Phasellus convallis, turpis interdum mollis dapibus, ipsum dui gravida odio, eu maximus massa nisi vel justo. Suspendisse quis sapien nec urna tincidunt dictum. Duis et nibh eu quam auctor pretium eget quis ligula. Duis at lectus sed ligula interdum elementum et a lectus. Nulla facilisi.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

Here is another change. Should result in a second commit.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }